"""initial schema

Revision ID: e789b1ae0d6b
Revises: 
Create Date: 2026-06-23 19:35:45.196284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e789b1ae0d6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counselors',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('languages_spoken', sa.JSON(), nullable=False),
    sa.Column('available_slots', sa.JSON(), nullable=False),
    sa.Column('current_load', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('leads',
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('preferred_language', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('raw_notes', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('assigned_counselor', sa.String(), nullable=True),
    sa.Column('counselor_slot', sa.String(), nullable=True),
    sa.Column('call_result', sa.String(), nullable=True),
    sa.Column('needs_captured', sa.String(), nullable=False),
    sa.Column('timestamp_created', sa.String(), nullable=False),
    sa.Column('last_updated', sa.String(), nullable=False),
    sa.Column('outreach_state', sa.String(), nullable=False),
    sa.Column('outreach_started_at', sa.DateTime(), nullable=True),
    sa.Column('outreach_attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_table('processed_webhooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('webhook_type', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('processed_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('webhook_type', 'external_id', name='uq_webhook_type_external_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_webhooks')
    op.drop_table('leads')
    op.drop_table('events')
    op.drop_table('counselors')
    # ### end Alembic commands ###
